AccountResales/src/TicketResales.Presentation/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AccountResales.Data.Repositories.Interfaces;
using AccountResales.Business.Models;
using System.Security.Claims;

namespace AccountResales.Presentation.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private IUserRepository userRep;
        private IOrderRepository orderRep;
        private IAccountRepository accountRep;

        public OrderController(IUserRepository userRep, IOrderRepository orderRep,
                                IAccountRepository accountRep)
        {
            this.userRep = userRep;
            this.orderRep = orderRep;
            this.accountRep = accountRep;
        }
        
        public IActionResult MyOrders()
        {
            User user = userRep.GetById(
                    Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value)
                    ); 
            List<Order> orders = orderRep.GetAllByBuyerId(user.Id).ToList();

            return View(orders);
        }

        [HttpDelete]
        public IActionResult Delete(int orderId)
        {
            try
            {
                Account account = orderRep.GetById(orderId).Account;
                account.Status = StatusAccount.Selling;
                accountRep.Update(account);
                orderRep.Delete(orderId);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error","Home");
            }
            return RedirectToAction("MyOrders");
        }
    }
}

AccountResales/src/TicketResales.Presentation/Views/Shared/_Layout.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder
@using AccountResales.Business.Models
@using System.Security.Claims;



@inject IViewLocalizer Localizer
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@Localizer["Account resales"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="content-wrapper">
        <div class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@Localizer["Account resales"]</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value.Equals("Admin"))
                            {
                                <li><a asp-area="Admin" asp-controller="Admin" asp-action="Index">@Localizer["Site settings"]</a></li>

                            }
                            <li><a asp-area="" asp-controller="Order" asp-action="MyOrders">@Localizer["My orders"]</a></li>
                            <li><a asp-area="" asp-controller="Account" asp-action="MyAccounts">@Localizer["My accounts"]</a></li>
                        }

                    </ul>
                    @await Html.PartialAsync("_LoginPartial")

                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>AccountResales</p>
            </footer>
        </div>

    </div>
        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js"></script>
            <script src="~/js/typeahead.js"></script>
            <script src="~/js/dropdown-enhancement.js"></script>
            <script src="~/js/sorttable.js"></script>

        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
        </environment>

        @RenderSection("scripts", required: false)
</body>

</html>