AccountResales/src/TicketResales.Presentation/Models/UserAccountViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountResales.Presentation.Models.AccountViewModels
{
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.Text)]
        public string LastName { get; set; }

        [Required]
        [StringLength(15, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

AccountResales/src/TicketResales.Presentation/Models/UserAccountViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountResales.Presentation.Models.AccountViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "FirstName")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "LastName")]
        public string LastName { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required]
        [StringLength(15, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        [Display(Name = "Phone")]
        public string Phone { get; set; }


        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }



    }
}

AccountResales/src/TicketResales.Presentation/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using AccountResales.Presentation.Models;
using AccountResales.Presentation.Models.AccountViewModels;
using AccountResales.Presentation.Services;
using AccountResales.Business.Models;
using AccountResales.Data.Utils;
using Microsoft.Extensions.Localization;
using AccountResales.Data.Repositories.Interfaces;

namespace AccountResales.Presentation.Controllers
{
    public class UserAccountController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly IStringLocalizer<UserAccountController> localizer;
        private readonly IUserRepository userRep;
        

        public UserAccountController(
            UserManager<User> userManager, SignInManager<User> signInManager, IStringLocalizer<UserAccountController> loc,
            IUserRepository userRepository)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.userRep = userRepository;
            localizer = loc;
        }

        //
        // GET: /Account/Login
        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                string hashPassword = PasswordUtil.GetSHA1HashString(model.Password);
                var result = await signInManager.PasswordSignInAsync(model.LastName, hashPassword, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    User user = userRep.GetUserByLastName(model.LastName);

                    createClaim(user);

                    RouteData.Values["culture"] = user.Localization;
                    return RedirectToLocal(returnUrl);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, localizer["Incorrect login or password!"]);
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/Register
        [HttpGet]
        public IActionResult Register(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new User { Email = model.Email, FirstName = model.FirstName, LastName = model.LastName,
                                      Phone = model.Phone, Address = model.Address};
                var result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToLocal(returnUrl);
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Manage()
        {
            User user = userRep.GetById(
                    Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value)
                    );
           
            return View(user);
        }

        [Authorize]
        [HttpPost]
        public string SaveInfo(int userId,/* string email, */string firstName,
                                string lastName, string address, string phone)
        {
            if(/*!string.IsNullOrWhiteSpace(email) && */!string.IsNullOrWhiteSpace(firstName) &&
                !string.IsNullOrWhiteSpace(lastName) && !string.IsNullOrWhiteSpace(address) &&
                !string.IsNullOrWhiteSpace(phone))
            {
                User user = userRep.GetById(
                    Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value)
                    );
                
                //if(!user.Email.Equals(email) && userRep.GetUserByEmail(email) != null)
                //{
                //    return localizer["This email busy!"];
                //}
                //user.Email = email;
                user.FirstName = firstName;
                user.LastName = lastName;
                user.Address = address;
                user.Phone = phone;
                userRep.Update(user);
            }

            return localizer["Success"];
        }

        [Authorize]
        [HttpPost]
        public string ChangePassword(int userId,string oldPassword, string newPassword, string confirmNewPassword)
        {
            User user = userRep.GetById(userId);
            if(!user.PasswordHash.Equals(PasswordUtil.GetSHA1HashString(oldPassword)))
            {
                return localizer["Wrong password!"];
            }
            if(!newPassword.Equals(confirmNewPassword))
            {
                return localizer["Wrong confirm password!"];
            }
            user.PasswordHash = PasswordUtil.GetSHA1HashString(newPassword);
            userRep.Update(user);
            return localizer["Success"];
        }

        //
        // POST: /Account/LogOff
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            await signInManager.SignOutAsync();
            await HttpContext.Authentication.SignOutAsync("Cookies");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }        
        
        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        private Task<User> GetCurrentUserAsync()
        {
            return userManager.GetUserAsync(HttpContext.User);
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        private async void createClaim(User user)
        {
            List<Claim> roleClaim = new List<Claim> {
                                        new Claim(ClaimsIdentity.DefaultRoleClaimType, user.Role.Name)
                                        };
            ClaimsIdentity id = new ClaimsIdentity(roleClaim, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
                                ClaimsIdentity.DefaultRoleClaimType);
            await HttpContext.Authentication.SignInAsync("Cookies", new ClaimsPrincipal(id));
        }
        #endregion
    }
}

AccountResales/src/TicketResales.Presentation/Views/UserAccount/Login.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using AccountResales.Business.Models;
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder

@inject IViewLocalizer Localizer
@model LoginViewModel

@inject SignInManager<User> SignInManager

@{
    ViewData["Title"] = "Log in";
}

<h2>@Localizer["Log in"]</h2>
<div class="row">
    <div class="col-md-8">
        <section>
            <form asp-controller="UserAccount" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
                <h4>@Localizer["Use a local account to log in."]</h4>
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="LastName" class="col-md-2 control-label">@Localizer["Last name"]</label>
                    <div class="col-md-10">
                        <input asp-for="LastName" class="form-control" placeholder="@Localizer["Last name"]"/>
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="col-md-2 control-label" >@Localizer["Password"]</label>
                    <div class="col-md-10">
                        <input asp-for="Password" class="form-control" placeholder="@Localizer["Password"]"/>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-default">@Localizer["Log in"]</button>
                    </div>
                </div>
                <p>
                    <a asp-action="Register" asp-route-returnurl="@ViewData["ReturnUrl"]">@Localizer["Register as a new user?"]</a>
                </p>                
            </form>
        </section>
    </div>    
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

AccountResales/src/TicketResales.Presentation/Views/UserAccount/Manage.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using AccountResales.Business.Models;
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder

@inject IViewLocalizer Localizer
@model User

@{
    ViewData["Title"] = "Log in";
}

<h2>@Localizer["Manage"]</h2>
<div class="row">
    <div class="col-md-10">
        <section>
            <div class="change-info">
                <div class="user-manage-form">
                    <h2>@Localizer["Change info"]</h2>
                    <div id="warnings"></div>
                    @*<div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["Email"]</label>
                        <input class="form-control input-sm" type="email" id="user-email" value="@Model.Email">
                    </div>*@
                    <div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["First name"]</label>
                        <input class="form-control input-sm" type="text" id="user-first-name" maxlength="15" value="@Model.FirstName">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["Last name"]</label>
                        <input class="form-control input-sm" type="text" id="user-last-name" maxlength="15" value="@Model.LastName">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["Address"]</label>
                        <input class="form-control input-sm" type="text" id="user-address" maxlength="25" value="@Model.Address">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["Phone"]</label>
                        <input class="form-control input-sm" type="text" id="user-phone" maxlength="15" value="@Model.Phone">
                    </div>
                    <a class="btn btn-default save-info" id="@Model.Id">@Localizer["Save information!"]</a>
                </div>

                <div class="change-password">
                    <h2>@Localizer["Change password"]</h2>
                    <div id="warnings-password"></div>

                    <div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["Old password"]</label>
                        <input class="form-control input-sm" type="password" id="old-password">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["New password"]</label>
                        <input class="form-control input-sm" type="password" id="new-password">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputSmall">@Localizer["Confirm new password"]</label>
                        <input class="form-control input-sm" type="password" id="confirm-new-password">
                    </div>

                    <a class="btn btn-default change-password-href" id="@Model.Id">@Localizer["Change password!"]</a>
                </div>

            </div>
        </section>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script type="text/javascript" src="~/js/manage.js"></script>
}

AccountResales/src/TicketResales.Presentation/Views/UserAccount/Register.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder

@inject IViewLocalizer Localizer
@model RegisterViewModel

@{
}

<h2>@Localizer["Registration"]</h2>

<form asp-controller="UserAccount" asp-action="Register" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
    <h4>@Localizer["Create a new account."]</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label">@Localizer["Email"]</label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label">@Localizer["First name"]</label>
        <div class="col-md-10">
            <input asp-for="FirstName" class="form-control" type="text"/>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label">@Localizer["Last name"]</label>
        <div class="col-md-10">
            <input asp-for="LastName" class="form-control" type="text"/>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Address" class="col-md-2 control-label">@Localizer["Address"]</label>
        <div class="col-md-10">
            <input asp-for="Address" class="form-control" type="text"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Phone" class="col-md-2 control-label">@Localizer["Phone"]</label>
        <div class="col-md-10">
            <input asp-for="Phone" class="form-control" type="text"/>
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label">@Localizer["Password"]</label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" type="password"/>
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label">@Localizer["Confirm password"]</label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control"/>
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">@Localizer["Registration"]</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}