AccountResales/src/TicketResales.Presentation/Areas/Admin/Controllers/FounderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AccountResales.Data.Repositories.Interfaces;
using AccountResales.Business.Models;
using Microsoft.Extensions.Localization;

namespace AccountResales.Presentation.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class FounderController : Controller
    {
        private IFounderRepository founderRep;
        private readonly IStringLocalizer<FounderController> localizer;
        private IOrganizationRepository organizationRep;

        public FounderController(IFounderRepository founderRep, IOrganizationRepository organizationRep,
            IStringLocalizer<FounderController> loc)
        {
            this.founderRep = founderRep;
            this.organizationRep = organizationRep;
            localizer = loc;
        }


        public IActionResult Index()
        {
            List<Founder> founders = founderRep.GetAll().ToList();
            return View("Founders", founders);
        }

        [HttpPost]
        public IActionResult Create(string founderName)
        {
            if(string.IsNullOrEmpty(founderName) || founderName.Length < 3)
            {
                return RedirectToAction("Error", "Admin");
            }
            if (founderRep.GetByName(founderName) != null)
            {
                return RedirectToAction("Error", "Admin"); //if this founder contains
            }
            else
            {
                founderRep.Create(new Founder() {Name = founderName });
                return RedirectToAction("Index");
            }
        }

        [HttpDelete]
        public IActionResult Delete(int founderId)
        {
            if(organizationRep.GetAllByFounderId(founderId).Count() > 0)
            {
                return RedirectToAction("Error", "Admin"); // if this use
            }
            founderRep.Delete(founderId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Update(int founderId, string founderName)
        {
            if (!string.IsNullOrEmpty(founderName) && founderName.Length < 3)
            {
                return RedirectToAction("Error", "Admin");
            }
            Founder founder = founderRep.GetById(founderId);
            founder.Name = founderName;
            founderRep.Update(founder);
            return RedirectToAction("Index");
        }
    }
}

AccountResales/src/TicketResales.Presentation/Areas/Admin/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AccountResales.Data.Repositories.Interfaces;
using AccountResales.Business.Models;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http.Internal;
using AccountResales.Data.Utils;
using System.IO;
using AccountResales.Presentation.Areas.Admin.Models.GameViewModels;

namespace AccountResales.Presentation.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class GameController : Controller
    {
        private IGameRepository gameRep;
        private IOrganizationRepository organizationRep;
        private IStringLocalizer<GameController> loc;
        private IAccountRepository accountRep;
        private IHostingEnvironment hostingEnvironment;

        public GameController(IOrganizationRepository organizationRep, IGameRepository gameRep,
                              IStringLocalizer<GameController> loc, IAccountRepository accountRep,
                              IHostingEnvironment hostingEnvironment)
        {
            this.organizationRep = organizationRep;
            this.gameRep = gameRep;
            this.accountRep = accountRep;
            this.loc = loc;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            List<Game> games = gameRep.GetAll().ToList();
            List<Organization> organizations = organizationRep.GetAll().ToList();

            GameViewModel gameVM = new GameViewModel() { Games = games, AllOrganizations = organizations };

            return View("Games", gameVM);
        }

        [HttpDelete]
        public IActionResult Delete(int gameId)
        {
            if (accountRep.GetAllByGameId(gameId).Count() != 0)
            {
                return RedirectToAction("Error", "Admin");//if this use
            }
            else
            {
                Game delGame = gameRep.GetById(gameId);
                if (delGame == null)
                {
                    return RedirectToAction("Error", "Admin");
                }
                else
                {
                    gameRep.Delete(gameId);
                    return RedirectToAction("Index");
                }
            }
        }

        [HttpPost]
        public IActionResult Update(int gameId, string bannerPath, string name, string dateString,
                             int organizationId, string description)
        {
            DateTime date;
            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(description)
                || !DateTime.TryParse(dateString, out date))
            {
                return RedirectToAction("Error", "Admin");
            }
            else
            {
                Game newGame = gameRep.GetById(gameId);
                if (bannerPath != null)
                {
                    newGame.Banner = bannerPath;
                }
                    newGame.Name = name;
                newGame.Date = date;
                newGame.Organization = organizationRep.GetById(organizationId);
                newGame.Description = description;
                gameRep.Update(newGame);
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Create(string bannerPath, string name, string dateString,
                             int organizationId, string description)
        {
            DateTime date;
            if (string.IsNullOrEmpty(bannerPath) || string.IsNullOrEmpty(name) || string.IsNullOrEmpty(description)
                || !DateTime.TryParse(dateString, out date))
            {
                return RedirectToAction("Error", "Admin"); 
            }
            else
            {
                Game newGame = new Game()
                {
                    Banner = bannerPath,
                    Name = name,
                    Date = date,
                    Organization = organizationRep.GetById(organizationId),
                    Description = description
                };
                gameRep.Create(newGame);
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public string ImageUpload()
        {
            IFormFile uploadFile = Request.Form.Files.FirstOrDefault();
            string dicName = RandomUtil.RandomInt(15).ToString();
            if (uploadFile != null)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(hostingEnvironment.WebRootPath + "/images/games/"
                                                                + dicName + "/"));
                using (var fileStream = new FileStream(hostingEnvironment.WebRootPath + "/images/games/"
                                                        + dicName + "/" + uploadFile.FileName, FileMode.Create))
                {
                    uploadFile.CopyToAsync(fileStream);
                }
            return ("/images/Games/" + dicName + '/' + uploadFile.FileName);
            }
            else
            {
                return null;
            }

        }
    }
}

AccountResales/src/TicketResales.Presentation/Areas/Admin/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AccountResales.Data.Repositories.Interfaces;
using AccountResales.Business.Models;
using Microsoft.Extensions.Localization;
using AccountResales.Presentation.Areas.Admin.Models.OrganizationViewModels;

namespace AccountResales.Presentation.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class OrganizationController : Controller
    {
        private IFounderRepository founderRep;
        private IGameRepository gameRep;
        private IOrganizationRepository organizationRep;
        private IStringLocalizer<OrganizationController> loc;

        public OrganizationController(IOrganizationRepository organizationRep, IFounderRepository founderRep, IGameRepository gameRep,
                              IStringLocalizer<OrganizationController> loc)
        {
            this.organizationRep = organizationRep;
            this.founderRep = founderRep;
            this.gameRep = gameRep;
            this.loc = loc;
        }

        public IActionResult Index()
        {
            List<Organization> organizations = organizationRep.GetAll().ToList();
            List<Founder> founders = founderRep.GetAll().ToList();

            OrganizationViewModel organizationVM = new OrganizationViewModel() { Organizations = organizations, AllFounders = founders };


            return View("Organizations", organizationVM);
        }

        [HttpDelete]
        public IActionResult Delete(int organizationId)
        {
            if (gameRep.GetByOrganizationId(organizationId).Count() != 0)
            {
                return RedirectToAction("Error", "Admin");//if this use
            }
            else
            {
                Organization organization = organizationRep.GetById(organizationId);
                if (organization == null)
                {
                    return RedirectToAction("Error", "Admin");
                }
                else
                {
                    organizationRep.Delete(organizationId);
                    return RedirectToAction("Index");
                }
            }
        }

        [HttpPost]
        public IActionResult Create(int founderId, string address, string name)
        {
            try
            {
                if (address.Length < 3 && name.Length < 3)
                {
                    return RedirectToAction("Error", "Admin");
                }
                else
                {
                    Organization organization = new Organization() {Founder = founderRep.GetById(founderId), Address = address, Name = name };
                    organizationRep.Create(organization);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Admin");
            }
        }


        [HttpPost]
        public IActionResult Update(int organizationId, int founderId, string address, string name)
        {
            try
            {
                if (address.Length < 3 && name.Length < 3)
                {
                    return RedirectToAction("Error", "Admin");
                }
                else
                {
                    Organization organization = organizationRep.GetById(organizationId);
                    organization.Founder = founderRep.GetById(founderId);
                    organization.Address = address;
                    organization.Name = name;
                    organizationRep.Update(organization);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Admin");
            }
        }
    }
}

AccountResales/src/TicketResales.Presentation/Areas/Admin/Views/Shared/_Layout.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@Localizer["Admin"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="row">
        <div class="col-lg-2">
            <div class="admin-nav">
                <div class="menu">
                    <div class="admin-header">
                        <a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                    </div>
                    <div class="content-hrefs">
                        <div class="list-group">
                            <a asp-area="admin" asp-controller="Founder" asp-action="Index">@Localizer["Founders"]</a>
                            <a asp-area="admin" asp-controller="Organization" asp-action="Index">@Localizer["Organizations"]</a>
                            <a asp-area="admin" asp-controller="Game" asp-action="Index">@Localizer["Games"]</a>
                            <a asp-area="admin" asp-controller="User" asp-action="Index">@Localizer["Users"]</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-10">
            @RenderBody()            
        </div>
    </div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>

</html>